insert into attachments (ID, Name, Code) values (1,'ACOG SIGHT','acog');
insert into attachments (ID, Name, Code) values (2,'REFLEX SIGHT','REFLEX');
insert into attachments (ID, Name, Code) values (4,'DRUM MAG','DRUM');
insert into attachments (ID, Name, Code) values (8,'DUAL MAG','DUALCLIP');
insert into attachments (ID, Name, Code) values (16,'RED DOT SIGHT','ELBIT');
insert into attachments (ID, Name, Code) values (32,'EXTENDED MAG','EXTCLIP');
insert into attachments (ID, Name, Code) values (64,'FLAMETHROWER','FT');
insert into attachments (ID, Name, Code) values (128,'GRENADE LAUNCHER','FL');
insert into attachments (ID, Name, Code) values (256,'GRIP','GRIP');
insert into attachments (ID, Name, Code) values (512,'INFRARED SCOPE','IR');
insert into attachments (ID, Name, Code) values (1024,'UPGRADED IRON SIGHTS','UPGRADESIGHT');
insert into attachments (ID, Name, Code) values (2048,'LOW POWER SCOPE','LPS');
insert into attachments (ID, Name, Code) values (4096,'MASTERKEY','MK');
insert into attachments (ID, Name, Code) values (8192,'SPEED RELOADER','SPEED');
insert into attachments (ID, Name, Code) values (16384,'RAPID FIRE','RF');
insert into attachments (ID, Name, Code) values (32768,'SUPPRESSOR','SILENCER');
insert into attachments (ID, Name, Code) values (65536,'SNUB NOSE','SNUB');
insert into attachments (ID, Name, Code) values (131072,'VARIABLE ZOOM','VZOOM');
insert into attachments (ID, Name, Code) values (262144,'DUAL WIELD','DW');
insert into attachments (ID, Name, Code) values (524288,'FULL AUTO UPGRADE','AUTO');
