insert into weapons (Name, Code, isPrimary, Class) values (M16,M16,1,AR)
insert into weapons (Name, Code, isPrimary, Class) values (M14,M14,1,AR)
insert into weapons (Name, Code, isPrimary, Class) values (FAMAS,FAMAS,1,AR)
insert into weapons (Name, Code, isPrimary, Class) values (AK-47,AK47,1,AR)
insert into weapons (Name, Code, isPrimary, Class) values (AUG,AUG,1,AR)
insert into weapons (Name, Code, isPrimary, Class) values (COMMANDO,COMMANDO,1,AR)
insert into weapons (Name, Code, isPrimary, Class) values (FN FAL,FNFAL,1,AR)
insert into weapons (Name, Code, isPrimary, Class) values (G11,G11,1,AR)
insert into weapons (Name, Code, isPrimary, Class) values (GALIL,GALIL,1,AR)
insert into weapons (Name, Code, isPrimary, Class) values (AK-74U,AK74U,1,SMG)
insert into weapons (Name, Code, isPrimary, Class) values (MAC 11,MAC11,1,SMG)
insert into weapons (Name, Code, isPrimary, Class) values (MP5K,MP5K,1,SMG)
insert into weapons (Name, Code, isPrimary, Class) values (MPL,MPL,1,SMG)
insert into weapons (Name, Code, isPrimary, Class) values (PM63,PM63,1,SMG)
insert into weapons (Name, Code, isPrimary, Class) values (SKORPION,SKORPION,1,SMG)
insert into weapons (Name, Code, isPrimary, Class) values (SPECTRE,SPECTRE,1,SMG)
insert into weapons (Name, Code, isPrimary, Class) values (UZI,UZI,1,SMG)
insert into weapons (Name, Code, isPrimary, Class) values (HK21,HK21,1,LMG)
insert into weapons (Name, Code, isPrimary, Class) values (M60,M60,1,LMG)
insert into weapons (Name, Code, isPrimary, Class) values (RPK,RPK,1,LMG)
insert into weapons (Name, Code, isPrimary, Class) values (STONER 63,STONER63,1,LMG)
insert into weapons (Name, Code, isPrimary, Class) values (HS-10,HS10,1,SHOTGUN)
insert into weapons (Name, Code, isPrimary, Class) values (SPAS-12,SPAS,1,SHOTGUN)
insert into weapons (Name, Code, isPrimary, Class) values (OLYMPIA,ROTTWEIL72,1,SHOTGUN)
insert into weapons (Name, Code, isPrimary, Class) values (STAKEOUT,ITHACA,1,SHOTGUN)
insert into weapons (Name, Code, isPrimary, Class) values (DRAGUNOV,DRAGUNOV,1,SNIPER)
insert into weapons (Name, Code, isPrimary, Class) values (WA2000,WA2000,1,SNIPER)
insert into weapons (Name, Code, isPrimary, Class) values (L96A1,L96A1,1,SNIPER)
insert into weapons (Name, Code, isPrimary, Class) values (PSG1,PSG1,1,SNIPER)
insert into weapons (Name, Code, isPrimary, Class) values (ASP,ASP,0,PISTOL)
insert into weapons (Name, Code, isPrimary, Class) values (M1911,M1911,0,PISTOL)
insert into weapons (Name, Code, isPrimary, Class) values (MAKAROV,MAKAROV,0,PISTOL)
insert into weapons (Name, Code, isPrimary, Class) values (PYTHON,PYTHON,0,PISTOL)
insert into weapons (Name, Code, isPrimary, Class) values (CZ75,CZ75,0,PISTOL)
insert into weapons (Name, Code, isPrimary, Class) values (M72 LAW,M72_LAW,0,LAUNCHER)
insert into weapons (Name, Code, isPrimary, Class) values (RPG,RPG,0,LAUNCHER)
insert into weapons (Name, Code, isPrimary, Class) values (STRELA-3,STRELA,0,LAUNCHER)
insert into weapons (Name, Code, isPrimary, Class) values (CHINA LAKE,CHINA LAKE,0,LAUNCHER)
insert into weapons (Name, Code, isPrimary, Class) values (BALLISTIC KNIFE,KNIFE_BALLISTIC,0,SPECIAL)
insert into weapons (Name, Code, isPrimary, Class) values (CROSSBOW,CROSSBOW_EXPLOSIVE,0,SPECIAL)
insert into weapons (Name, Code, isPrimary, Class) values (CONCUSSION GRENADE,CONCUSSION_GRENADE,0,EQUIPMENT)
insert into weapons (Name, Code, isPrimary, Class) values (FLASH GRENADE,FLASH_GRENADE,0,EQUIPMENT)
insert into weapons (Name, Code, isPrimary, Class) values (FRAG GRENADE,FRAG_GRENADE,0,EQUIPMENT)
insert into weapons (Name, Code, isPrimary, Class) values (SEMTEX GRENADE,STICKY_GRENADE,0,EQUIPMENT)
insert into weapons (Name, Code, isPrimary, Class) values (NOVA GAS,TABUN_GAS,0,EQUIPMENT)
insert into weapons (Name, Code, isPrimary, Class) values (WILLY PETE,WILLY_PETE,0,EQUIPMENT)
insert into weapons (Name, Code, isPrimary, Class) values (CLAYMORE,CLAYMORE,0,EQUIPMENT)
insert into weapons (Name, Code, isPrimary, Class) values (C4,SATCHEL_CHARGE,0,EQUIPMENT)
insert into weapons (Name, Code, isPrimary, Class) values (TOMAHAWK,HATCHET,0,EQUIPMENT)
insert into weapons (Name, Code, isPrimary, Class) values (ROLLING THUNDER,AIRSTRIKE,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (SENTRY GUN,AUTO_GUN_TURRET,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (ATTACK HELICOPTER,COBRA_20MM_COMLINK,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (ATTACK DOGS,DOG_BITE,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (GUNSHIP (MINIGUN) ,HIND_MINIGUN_PILOT_FIRSTPERSON,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (GUNSHIP (ROCKET),HIND_ROCKETS_FIRSTPERSON,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (CHOPPER GUNNER,HUEY_MINIGUN_GUNNER,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (VALKRIE ROCKETS,M220_TOW,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (MORTAR TEAM,MORTAR,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (NAPALM STIKE,NAPALM,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (RC-XD,RCBOMB,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (DEATH MACHINE ,MINIGUN_MP,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (GRIM REAPER ,M202_FLASH,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (EXPLOSIVE BOLT,EXPLOSIVE_BOLT,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (EXPLODABLE BARREL,EXPLODABLE_BARREL,0,KILLSTREAK)
insert into weapons (Name, Code, isPrimary, Class) values (GRENADE LAUNCHER,GL,0,ATTACHMENT)
insert into weapons (Name, Code, isPrimary, Class) values (FLAMETHROWER,FT,0,ATTACHMENT)
insert into weapons (Name, Code, isPrimary, Class) values (MASTERKEY,MK,0,ATTACHMENT)
insert into weapons (Name, Code, isPrimary, Class) values (KNIFE,KNIFE ,0,MISC)
insert into weapons (Name, Code, isPrimary, Class) values (WORLD,WORLD,0,MISC)
insert into weapons (Name, Code, isPrimary, Class) values (NONE ,NONE,0,MISC)
insert into weapons (Name, Code, isPrimary, Class) values (BOMB,BRIEFCASE_BOMB,0,MISC)
insert into weapons (Name, Code, isPrimary, Class) values (CAR,DESTRUCTIBLE_CAR,0,MISC)
